FROM node:alpine

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install
RUN apk update
RUN apk add
RUN apk add ffmpeg

COPY ./ .

EXPOSE 8080

HEALTHCHECK --interval=120s --timeout=60s CMD curl -s http://localhost:8080 || exit 1

CMD ["npm", "run", "dev:hmr"]
