version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - gains-network
    volumes:
      - postgres-data:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      REDIS_URL: ${REDIS_URL}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - gains-network
    volumes:
      - redis-data:/data/redis

  gains:
    image: gains
    container_name: gains
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    restart: always
    stdin_open: true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - gains-network
    depends_on:
      - postgres
      - redis

networks:
  gains-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
