FROM node:24-alpine

RUN apk update && apk add --no-cache ffmpeg curl

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node ./ ./

RUN npm run build

USER node

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1

CMD ["npm", "run", "start"]
