services:
  mailhog:
    container_name: mailhot
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - gains-network

  gains:
    image: gains
    container_name: gains
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    ports:
      - ${PORT}:${PORT}
      - ${VUE_PORT}:${VUE_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - gains-network
    depends_on:
      mailhog:
        condition: service_started

networks:
  gains-network:
    driver: bridge
